{% set import_path = "gitlab.com/gitlab-org/gitlab-runner" %}
{% set version = "12.5.0" %}
{% set branch = '-'.join(version.split('.')[:2] +['stable']) %}
{% set built = datetime.datetime.now().isoformat() %}

{% set name = import_path.split('/')[-1] %}
{% set pkg_src = ('src/'+import_path).replace("/", os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ import_path }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.bz2
    sha256: 576220689504cee1a1be3f4f0ad4f191ba0a1a546667003b59ad11de2e2659d9

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    {% set flags = dict(VERSION=version, REVISION="%PKG_BUILDNUM%" if win else "$PKG_BUILDNUM", BRANCH=branch, BUILT=built) %}
    - go install -v -ldflags "{% for key,value in flags.items() %}-X {{ import_path }}/common.{{ key }}='{{ value }}' {% endfor %}" .

requirements:
  build:
    - {{ compiler("go") }}

test:
  commands:
    - gitlab-runner --version

about:
  summary: The official GitLab CI runner written in Go
  license: MIT
  license_family: MIT
  license_file: {{ pkg_src }}/LICENSE
  home: https://gitlab.com/gitlab-org/gitlab-runner
  dev_url: https://gitlab.com/gitlab-org/gitlab-runner
  doc_url: https://docs.gitlab.com/runner/

extra:
  recipe-maintainers:
    - duncanmmacleod
    - sodre
