travis:
  secure:
    BINSTAR_TOKEN: G0yqZYDwz2UijSm7Kwkw/eJgCvO4P3mDXI7rswBgGs6RBxjeldsHKe1tvQzizPoa16M/yq9evqmRJAnTYeb9AyFWd1bAj1MZumGwxZ1Yl+xIJiUHGP8qOm8S53h2bQBVaZuUlMYmMEe+XqX3CDTFCEK+/S7Wg+gM7yoNHw/ZYzgNwuS+E8Ozh6MSHTT7cBE7MRzVuhaKIzA3CBIZWiHHrAbvWEqib8m+EtQaLBYvWe7B9ndfppCWxG+GkXcW3wPUqgJ7zv6TjMAiQJLjvclhiQBolZnVdz4ZcSBDZK7kvIStBQDl2ZuDu1egRaaZ2uJ5GIlbUxr51sya+jJ53cCHPJWr6WXuMRxBhSBhiJ6qq7dvOY1PyhM+3YOjSix8aOf697zDE9KIbQOdRm0hRWu5FqkTgtL4qnPk4RpMucebUmGMyGBA7m1Rhx2VSzdYpaulDf8yfMndXsZimyHXmgNbjjWArtOe0WdG8IKv/hyTkKPS8dqlOkSNVCdsRAQHLUvWQWSxYrnDdb1UOiJMysAYUWCSNv/QIbTU6pYIoGcAGpOOQbRNY78nw0xLK2GWHxYSuf37xd2Qgu/X6kQWxxFIH6Vmu8/2IwXbE+Bxh7CbP1ffZuUXSyB/62xHaQ2xVBXczFoSoRNH4yF/6wCBS19AGxI/VfkkADJjj4Nnx6vszBA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
